# Generated by Django 4.1.6 on 2023-05-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Domestic Violence', 'Domestic Violence'), ('Family Violence', 'Family Violence'), ('Sexual Violence and Harassment', 'Sexual Violence and Harassment'), ('Non Physical form of abuse', 'Non Physical form of abuse')], max_length=50, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('evi_format', models.CharField(blank=True, max_length=50, null=True)),
                ('evidence', models.FileField(upload_to='')),
            ],
        ),
    ]
